//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public int id_employment { get; set; }
        public int id_employe { get; set; }
        public int id_position { get; set; }
        public int id_service { get; set; }
        public double price { get; set; }
        public int id_party { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Party Party { get; set; }
        public virtual Position Position { get; set; }
        public virtual Services Services { get; set; }
    }
}
